<?xml version="1.0"?>
<package format="2">
  <name>teleop_arm</name>
  <version>0.0.1</version>
  <description>Z1 master/slave teleop nodes (C++, unitree_arm_sdk).</description>

  <maintainer email="mason.zqy@gmail.com">ZQY</maintainer>
  <license>MIT</license>

  <buildtool_depend>catkin</buildtool_depend>

  <depend>roscpp</depend>
  <depend>std_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>teleop_msgs</depend>
  <depend>tf2</depend>
  <depend>tf2_geometry_msgs</depend>

  <export/>
</package>
